"""
Configuration placeholders for the Business Entity Resolution Classifier Module.

This file provides centralized settings, paths, and hyperparameters for training,
evaluating, and serving the classifier.

NOTE FOR PAIRWISE DEVELOPER:
Once the pairwise feature engineering module is finalized, populate `FEATURE_COLUMNS`
with the exact list of numerical feature names generated by your module.
Do NOT modify the identifier column settings unless the pairwise interface changes.
"""
from pathlib import Path
from typing import Dict, Any, List

# -----------------------------------------------------------------------------
# Base Directories & Data Paths
# -----------------------------------------------------------------------------
PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent

# Input & Output Paths
# Placeholders: The pairwise developer will produce the input feature files.
INPUT_FEATURE_PATH: Path = PROJECT_ROOT / "data" / "pairwise_features.parquet"
OUTPUT_DIR: Path = PROJECT_ROOT / "output"
PREDICTION_OUTPUT_PATH: Path = OUTPUT_DIR / "matching_results.tsv"

# Model & Threshold Artifact Paths
MODEL_ARTIFACT_PATH: Path = OUTPUT_DIR / "classifier_model.joblib"
THRESHOLD_ARTIFACT_PATH: Path = OUTPUT_DIR / "optimal_threshold.json"

# -----------------------------------------------------------------------------
# Dataset Schema & Column Names
# -----------------------------------------------------------------------------
S1_ID_COL: str = "source1_entity_id"
TARGET_ID_COL: str = "target_entity_id"
TARGET_SOURCE_COL: str = "target_source"
LABEL_COL: str = "is_match"

# Required identifier columns expected in the pairwise dataframe
REQUIRED_ID_COLUMNS: List[str] = [S1_ID_COL, TARGET_ID_COL, TARGET_SOURCE_COL]

# Pairwise Feature Columns (matching src/features/pair_features.py)
FEATURE_COLUMNS: List[str] = [
    # Name Similarity Features
    "name_key_eq", "name_compact_eq", "name_ratio", "name_token_sort",
    "name_token_set", "name_partial", "name_jw", "name_tok_jacc",
    "name_3gram_jacc", "name_compact_ratio", "name_len_ratio", "name_ntok_ratio",
    "legal_agree", "cand_is_domain", "script_diff", "cand_non_latin",
    # Address Similarity Features
    "addr_key_eq", "addr_ratio", "addr_token_set", "addr_token_sort",
    "addr_tok_jacc", "addr_len_ratio", "house_eq", "house_suffix", "house_sim",
    "numbers_jacc", "state_agree", "postal_agree", "landmark_jacc", "addr_missing",
    # Source Feature
    "cand_source",
    # Context & Ranking Features
    "name_token_set_rank", "name_token_set_gap",
    "addr_token_set_rank", "addr_token_set_gap",
    "name_ratio_rank", "name_ratio_gap",
    "cand_n_s1", "cand_rank_blk",  # measured on the full split (src/features/global_context.py)
    # v2 (26 Sep): rarity-weighted overlap, damaged-digit numbers, transliteration skeleton.
    # +0.3 pt macro F0.5 on 30k dev S1s (out-of-fold, full ground truth), see reports/PHASE23_RESULTS.md
    "addr_idf_jacc", "addr_rare_shared", "addr_idf_max_shared", "name_idf_jacc", "name_rare_shared",
    "house_in_numbers", "numbers_near_frac", "name_skel_ratio", "name_skel_eq",
]

# -----------------------------------------------------------------------------
# Model Hyperparameters & Training Settings
# -----------------------------------------------------------------------------
# Default parameters for LightGBM / Sklearn tabular gradient boosting classifier
# v2 (26 Sep): bigger trees + early stopping on the validation S1s; subsample_freq=1 so bagging
# actually runs (LightGBM ignores subsample without it). +0.36 pt on 30k dev S1s vs the old
# 300 trees / depth 6 / 31 leaves.
MODEL_PARAMS: Dict[str, Any] = {
    "n_estimators": 3000,          # upper bound; early stopping picks the real number (~300-400)
    "learning_rate": 0.05,
    "num_leaves": 127,
    "min_child_samples": 100,
    "subsample": 0.8,
    "subsample_freq": 1,
    "colsample_bytree": 0.8,
    "reg_lambda": 1.0,
    "random_state": 42,
    "n_jobs": -1,
    "verbose": -1,
}
EARLY_STOPPING_ROUNDS: int = 50

VALIDATION_SPLIT: float = 0.2
RANDOM_SEED: int = 42

# -----------------------------------------------------------------------------
# Threshold Optimization Parameters ($F_{0.5}$ Metric)
# -----------------------------------------------------------------------------
DEFAULT_THRESHOLD: float = 0.5
THRESHOLD_MIN: float = 0.05
THRESHOLD_MAX: float = 0.95
THRESHOLD_STEP: float = 0.01
