"""
Configuration placeholders for the Business Entity Resolution Classifier Module.

This file provides centralized settings, paths, and hyperparameters for training,
evaluating, and serving the classifier.

NOTE FOR PAIRWISE DEVELOPER:
Once the pairwise feature engineering module is finalized, populate `FEATURE_COLUMNS`
with the exact list of numerical feature names generated by your module.
Do NOT modify the identifier column settings unless the pairwise interface changes.
"""
from pathlib import Path
from typing import Dict, Any, List

# -----------------------------------------------------------------------------
# Base Directories & Data Paths
# -----------------------------------------------------------------------------
PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent

# Input & Output Paths
# Placeholders: The pairwise developer will produce the input feature files.
INPUT_FEATURE_PATH: Path = PROJECT_ROOT / "data" / "pairwise_features.parquet"
OUTPUT_DIR: Path = PROJECT_ROOT / "output"
PREDICTION_OUTPUT_PATH: Path = OUTPUT_DIR / "matching_results.tsv"

# Model & Threshold Artifact Paths
MODEL_ARTIFACT_PATH: Path = OUTPUT_DIR / "classifier_model.joblib"
THRESHOLD_ARTIFACT_PATH: Path = OUTPUT_DIR / "optimal_threshold.json"

# -----------------------------------------------------------------------------
# Dataset Schema & Column Names
# -----------------------------------------------------------------------------
S1_ID_COL: str = "source1_entity_id"
TARGET_ID_COL: str = "target_entity_id"
TARGET_SOURCE_COL: str = "target_source"
LABEL_COL: str = "is_match"

# Required identifier columns expected in the pairwise dataframe
REQUIRED_ID_COLUMNS: List[str] = [S1_ID_COL, TARGET_ID_COL, TARGET_SOURCE_COL]

# TODO (Pairwise Developer): Update this list with final pairwise feature column names.
# Example placeholder: ["name_jaccard", "address_levenshtein", "postal_match"]
FEATURE_COLUMNS: List[str] = []

# -----------------------------------------------------------------------------
# Model Hyperparameters & Training Settings
# -----------------------------------------------------------------------------
# Default parameters for LightGBM / Sklearn tabular gradient boosting classifier
MODEL_PARAMS: Dict[str, Any] = {
    "n_estimators": 300,
    "learning_rate": 0.05,
    "max_depth": 6,
    "num_leaves": 31,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "random_state": 42,
    "n_jobs": -1,
}

VALIDATION_SPLIT: float = 0.2
RANDOM_SEED: int = 42

# -----------------------------------------------------------------------------
# Threshold Optimization Parameters ($F_{0.5}$ Metric)
# -----------------------------------------------------------------------------
DEFAULT_THRESHOLD: float = 0.5
THRESHOLD_MIN: float = 0.05
THRESHOLD_MAX: float = 0.95
THRESHOLD_STEP: float = 0.01
