"""
Blocker quality on the 100k dev set: recall, perfect-classifier F0.5 ceiling, candidate pool size,
and why the missed true pairs were missed - for one or several candidate caps from ONE blocker run.

The blocker cache stores each candidate's rank within its S1 (0 = best), so smaller caps are just
`rank < cap` filters on a cache built with the largest cap. The blocker also saves the UNCAPPED
dev pairs (data/cache/precap_dev_{split}.parquet), which splits misses into:
  cut by cap       the pair was generated by some rule but ranked below the cap
  not generated    no rule produced it (key didn't match, or the key block was too crowded)

Usage:
    python -m src.blocking.check_recall                          # evaluate the existing train cache
    python -m src.blocking.check_recall --caps 20 30 50          # several caps (cache built with >= 50)
    python -m src.blocking.check_recall --rebuild --max-candidates 50 --caps 20 30 50
    python -m src.blocking.check_recall --tag ranked_v2          # label the run in the JSON
"""
import argparse
import json
import time

import numpy as np
import pandas as pd

from ..config import WORK_DIR, DEV_IDS_FILE, OUTPUT_DIR
from ..data import id_to_int, gt_pairs
from .blocker import MultiPassBlocker, CACHE_DIR, precap_dev_path


def _dev_truth(dev_ints: np.ndarray) -> pd.DataFrame:
    path = WORK_DIR / "cache" / "truth_train.parquet"
    if path.exists():
        truth = pd.read_parquet(path)
    else:
        gp = gt_pairs()
        truth = pd.DataFrame({"s1_int": id_to_int(gp.s1_id.values), "tg_int": id_to_int(gp.match_id.values)})
    return truth[truth.s1_int.isin(set(dev_ints))].reset_index(drop=True)


def evaluate(cands: pd.DataFrame, truth: pd.DataFrame, dev_ints: np.ndarray, precap=None) -> dict:
    """Metrics for one candidate set restricted to the dev S1s."""
    n_true = truth.groupby("s1_int").size().reindex(dev_ints, fill_value=0).values
    hit = truth.merge(cands[["s1_int", "tg_int"]], on=["s1_int", "tg_int"])
    tp = hit.groupby("s1_int").size().reindex(dev_ints, fill_value=0).values
    ncand = cands.groupby("s1_int").size().reindex(dev_ints, fill_value=0).values

    # perfect classifier on these candidates: predicts exactly the true candidates (precision 1)
    rec = np.where(n_true > 0, tp / np.maximum(n_true, 1), 0.0)
    f05 = np.where(n_true == 0, 1.0, np.where(tp > 0, 1.25 * rec / (0.25 + rec), 0.0))

    res = {
        "recall_pct": round(100 * tp.sum() / max(n_true.sum(), 1), 2),
        "oracle_macro_f05": round(float(f05.mean()), 4),
        "mean_candidates": round(float(ncand.mean()), 2),
        "p50_candidates": int(np.percentile(ncand, 50)),
        "p95_candidates": int(np.percentile(ncand, 95)),
        "max_candidates": int(ncand.max()),
        "coverage_pct": round(100 * float((ncand > 0).mean()), 2),
        "s1_true_but_no_true_candidate": int(((n_true > 0) & (tp == 0)).sum()),
    }
    if precap is not None:
        missed = truth.merge(cands[["s1_int", "tg_int"]], on=["s1_int", "tg_int"], how="left", indicator=True)
        missed = missed[missed._merge == "left_only"][["s1_int", "tg_int"]]
        gen = missed.merge(precap[["s1_int", "tg_int"]], on=["s1_int", "tg_int"], how="inner")
        n_miss = max(len(missed), 1)
        res["missed_pairs"] = int(len(missed))
        res["missed_cut_by_cap_pct"] = round(100 * len(gen) / n_miss, 1)
        res["missed_not_generated_pct"] = round(100 * (len(missed) - len(gen)) / n_miss, 1)
        res["uncapped_recall_pct"] = round(100 * len(truth.merge(precap[["s1_int", "tg_int"]], on=["s1_int", "tg_int"]))
                                           / max(len(truth), 1), 2)
        res["uncapped_mean_candidates"] = round(len(precap) / len(dev_ints), 2)
    return res


def check_recall(rebuild: bool = False, max_candidates: int = 50, caps=None, split: str = "train",
                 tag: str = "") -> dict:
    t0 = time.time()
    cache_path = CACHE_DIR / f"candidate_pairs_{split}.parquet"
    if rebuild or not cache_path.exists():
        print(f"Building candidate cache with max_candidates={max_candidates}...")
        MultiPassBlocker(max_candidates_per_entity=max_candidates).build_candidates(split=split)

    dev_ints = id_to_int(pd.read_csv(DEV_IDS_FILE, dtype=str)["s1_id"].values)
    truth = _dev_truth(dev_ints)
    cols = ["s1_int", "tg_int"]
    cache = pd.read_parquet(cache_path)
    cache = cache[cache.s1_int.isin(set(dev_ints))]
    has_rank = "rank" in cache.columns
    built_cap = int(cache.groupby("s1_int").size().max()) if len(cache) else 0
    pp = precap_dev_path(split)
    precap = pd.read_parquet(pp, columns=cols) if pp.exists() else None

    caps = sorted(caps) if caps else [built_cap]
    results = {"tag": tag, "split": split, "dev_entities": int(len(dev_ints)),
               "dev_true_pairs": int(len(truth)), "cache_cap": built_cap, "by_cap": {}}
    for cap in caps:
        if cap > built_cap and built_cap:
            print(f"  cap {cap} > cache cap {built_cap}: rebuild with --max-candidates {cap}")
            continue
        if cap < built_cap and not has_rank:
            print(f"  cap {cap}: cache has no rank column (old blocker), skipping")
            continue
        sub = cache[cache["rank"] < cap] if has_rank else cache
        results["by_cap"][str(cap)] = evaluate(sub, truth, dev_ints, precap)

    print(f"\n{'=' * 96}\nBLOCKER CHECK on {len(dev_ints):,} dev S1 ({len(truth):,} true pairs)"
          f"{' [' + tag + ']' if tag else ''}\n{'=' * 96}")
    hdr = f"{'cap':>5}{'recall':>9}{'oracle F0.5':>13}{'mean cand':>11}{'p95':>6}{'coverage':>10}{'missed: cut by cap':>21}{'not generated':>15}"
    print(hdr)
    for cap, r in results["by_cap"].items():
        print(f"{cap:>5}{r['recall_pct']:>8.2f}%{r['oracle_macro_f05']:>13.4f}{r['mean_candidates']:>11.2f}"
              f"{r['p95_candidates']:>6}{r['coverage_pct']:>9.2f}%"
              f"{str(r.get('missed_cut_by_cap_pct', '-')) + '%':>21}{str(r.get('missed_not_generated_pct', '-')) + '%':>15}")
    if precap is not None and results["by_cap"]:
        r = next(iter(results["by_cap"].values()))
        print(f"no cap at all: recall {r['uncapped_recall_pct']:.2f}% with {r['uncapped_mean_candidates']:.1f} candidates/S1")
    print(f"({time.time() - t0:.0f}s)")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUTPUT_DIR / (f"blocking_recall_check_{tag}.json" if tag else "blocking_recall_check.json")
    out.write_text(json.dumps(results, indent=2))
    print(f"saved {out}")
    return results


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Blocker recall / ceiling / pool size on the dev set.")
    ap.add_argument("--rebuild", action="store_true", help="Rebuild the candidate cache first.")
    ap.add_argument("--max-candidates", type=int, default=50, help="Cap used when rebuilding.")
    ap.add_argument("--caps", type=int, nargs="+", help="Caps to evaluate (<= the cache's cap).")
    ap.add_argument("--split", default="train", choices=["train"])
    ap.add_argument("--tag", default="", help="Label for this run (JSON file name).")
    a = ap.parse_args()
    check_recall(rebuild=a.rebuild, max_candidates=a.max_candidates, caps=a.caps, split=a.split, tag=a.tag)
